services:

  bat-signal-backend:
    container_name: bat-signal
    image: bat-signal-img
    build:
      dockerfile: ./Dockerfile
    working_dir: /home/deno/dingDong
    command: bash -c "\
      deno cache server.ts && \
      timeout 10s deno -A server.ts || [ $? -eq 124 ] || exit 1 && \
      deno run -NRE server.ts"
    volumes:
      - ./:/home/deno/dingDong
    ports:
      - '8080:8080'
  

