services:

  bat-signal-backend:
    container_name: bat-signal
    image: bat-signal-img
    restart: always
    build:
      dockerfile: ./Dockerfile
    working_dir: /home/deno/dingDong
    command: bash -c "\
      deno cache server.ts && \
      timeout 10s deno run --unstable-broadcast-channel -NRE server.ts" || [ $? -eq 124 ] || exit 1 && \
      
    volumes:
      - ./:/home/deno/dingDong
    ports:
      - '8080:8080'
  

